import {
  type Editor,
  SpecialCharacters,
} from 'ckeditor5';

export function SpecialCharactersEmoji(editor: Editor): void {
  const specialCharacters = editor.plugins.get(SpecialCharacters);
  // Smileys & Emotion - Faces
  specialCharacters.addItems('Emoji: Smileys', [
    { title: 'grinning face', character: '😀' },
    { title: 'grinning face with big eyes', character: '😃' },
    { title: 'grinning face with smiling eyes', character: '😄' },
    { title: 'beaming face with smiling eyes', character: '😁' },
    { title: 'grinning squinting face', character: '😆' },
    { title: 'grinning face with sweat', character: '😅' },
    { title: 'rolling on the floor laughing', character: '🤣' },
    { title: 'face with tears of joy', character: '😂' },
    { title: 'slightly smiling face', character: '🙂' },
    { title: 'upside down face', character: '🙃' },
    { title: 'winking face', character: '😉' },
    { title: 'smiling face with smiling eyes', character: '😊' },
    { title: 'smiling face with halo', character: '😇' },
    { title: 'smiling face with hearts', character: '🥰' },
    { title: 'smiling face with heart-eyes', character: '😍' },
    { title: 'star-struck', character: '🤩' },
    { title: 'face blowing a kiss', character: '😘' },
    { title: 'kissing face', character: '😗' },
    { title: 'smiling face', character: '☺️' },
    { title: 'kissing face with closed eyes', character: '😚' },
    { title: 'kissing face with smiling eyes', character: '😙' },
  ]);

  // Face Expressions
  specialCharacters.addItems('Emoji: Expressions', [
    { title: 'face savoring food', character: '😋' },
    { title: 'face with tongue', character: '😛' },
    { title: 'winking face with tongue', character: '😜' },
    { title: 'zany face', character: '🤪' },
    { title: 'squinting face with tongue', character: '😝' },
    { title: 'money-mouth face', character: '🤑' },
    { title: 'smiling face with open hands', character: '🤗' },
    { title: 'face with hand over mouth', character: '🤭' },
    { title: 'shushing face', character: '🤫' },
    { title: 'thinking face', character: '🤔' },
    { title: 'zipper-mouth face', character: '🤐' },
    { title: 'face with raised eyebrow', character: '🤨' },
    { title: 'neutral face', character: '😐' },
    { title: 'expressionless face', character: '😑' },
    { title: 'face without mouth', character: '😶' },
    { title: 'smirking face', character: '😏' },
    { title: 'unamused face', character: '😒' },
    { title: 'face with rolling eyes', character: '🙄' },
    { title: 'grimacing face', character: '😬' },
    { title: 'lying face', character: '🤥' },
  ]);

  // Negative Faces
  specialCharacters.addItems('Emoji: Negative', [
    { title: 'relieved face', character: '😌' },
    { title: 'pensive face', character: '😔' },
    { title: 'sleepy face', character: '😪' },
    { title: 'drooling face', character: '🤤' },
    { title: 'sleeping face', character: '😴' },
    { title: 'face with medical mask', character: '😷' },
    { title: 'face with thermometer', character: '🤒' },
    { title: 'face with head-bandage', character: '🤕' },
    { title: 'nauseated face', character: '🤢' },
    { title: 'face vomiting', character: '🤮' },
    { title: 'sneezing face', character: '🤧' },
    { title: 'hot face', character: '🥵' },
    { title: 'cold face', character: '🥶' },
    { title: 'woozy face', character: '🥴' },
    { title: 'dizzy face', character: '😵' },
    { title: 'exploding head', character: '🤯' },
    { title: 'cowboy hat face', character: '🤠' },
    { title: 'partying face', character: '🥳' },
    { title: 'smiling face with sunglasses', character: '😎' },
    { title: 'nerd face', character: '🤓' },
    { title: 'face with monocle', character: '🧐' },
  ]);

  // Concerned Faces
  specialCharacters.addItems('Emoji: Concerned', [
    { title: 'confused face', character: '😕' },
    { title: 'worried face', character: '😟' },
    { title: 'slightly frowning face', character: '🙁' },
    { title: 'frowning face', character: '☹️' },
    { title: 'face with open mouth', character: '😮' },
    { title: 'hushed face', character: '😯' },
    { title: 'astonished face', character: '😲' },
    { title: 'flushed face', character: '😳' },
    { title: 'pleading face', character: '🥺' },
    { title: 'frowning face with open mouth', character: '😦' },
    { title: 'anguished face', character: '😧' },
    { title: 'fearful face', character: '😨' },
    { title: 'anxious face with sweat', character: '😰' },
    { title: 'sad but relieved face', character: '😥' },
    { title: 'crying face', character: '😢' },
    { title: 'loudly crying face', character: '😭' },
    { title: 'face screaming in fear', character: '😱' },
    { title: 'confounded face', character: '😖' },
    { title: 'persevering face', character: '😣' },
    { title: 'disappointed face', character: '😞' },
    { title: 'downcast face with sweat', character: '😓' },
    { title: 'weary face', character: '😩' },
    { title: 'tired face', character: '😫' },
    { title: 'yawning face', character: '🥱' },
  ]);

  // Angry Faces
  specialCharacters.addItems('Emoji: Angry', [
    { title: 'face with steam from nose', character: '😤' },
    { title: 'pouting face', character: '😡' },
    { title: 'angry face', character: '😠' },
    { title: 'face with symbols on mouth', character: '🤬' },
    { title: 'smiling face with horns', character: '😈' },
    { title: 'angry face with horns', character: '👿' },
    { title: 'skull', character: '💀' },
    { title: 'skull and crossbones', character: '☠️' },
  ]);

  // Gestures & Body Parts
  specialCharacters.addItems('Emoji: Hands', [
    { title: 'clapping hands', character: '👏' },
    { title: 'raising hands', character: '🙌' },
    { title: 'open hands', character: '👐' },
    { title: 'palms up together', character: '🤲' },
    { title: 'handshake', character: '🤝' },
    { title: 'folded hands', character: '🙏' },
    { title: 'writing hand', character: '✍️' },
    { title: 'nail polish', character: '💅' },
    { title: 'waving hand', character: '👋' },
    { title: 'raised back of hand', character: '🤚' },
    { title: 'hand with fingers splayed', character: '🖐️' },
    { title: 'raised hand', character: '✋' },
    { title: 'vulcan salute', character: '🖖' },
    { title: 'OK hand', character: '👌' },
    { title: 'pinching hand', character: '🤏' },
    { title: 'victory hand', character: '✌️' },
    { title: 'crossed fingers', character: '🤞' },
    { title: 'love-you gesture', character: '🤟' },
    { title: 'sign of the horns', character: '🤘' },
    { title: 'call me hand', character: '🤙' },
    { title: 'thumbs up', character: '👍' },
    { title: 'thumbs down', character: '👎' },
    { title: 'raised fist', character: '✊' },
    { title: 'oncoming fist', character: '👊' },
    { title: 'left-facing fist', character: '🤛' },
    { title: 'right-facing fist', character: '🤜' },
  ]);

  // Hearts & Symbols
  specialCharacters.addItems('Emoji: Hearts', [
    { title: 'red heart', character: '❤️' },
    { title: 'orange heart', character: '🧡' },
    { title: 'yellow heart', character: '💛' },
    { title: 'green heart', character: '💚' },
    { title: 'blue heart', character: '💙' },
    { title: 'purple heart', character: '💜' },
    { title: 'brown heart', character: '🤎' },
    { title: 'black heart', character: '🖤' },
    { title: 'white heart', character: '🤍' },
    { title: 'heart with arrow', character: '💘' },
    { title: 'heart with ribbon', character: '💝' },
    { title: 'sparkling heart', character: '💖' },
    { title: 'growing heart', character: '💗' },
    { title: 'beating heart', character: '💓' },
    { title: 'revolving hearts', character: '💞' },
    { title: 'two hearts', character: '💕' },
    { title: 'heart decoration', character: '💟' },
    { title: 'heart exclamation', character: '❣️' },
    { title: 'broken heart', character: '💔' },
    { title: 'heart on fire', character: '❤️‍🔥' },
    { title: 'mending heart', character: '❤️‍🩹' },
  ]);

  // Common Symbols
  specialCharacters.addItems('Emoji: Common Symbols', [
    { title: 'fire', character: '🔥' },
    { title: 'star', character: '⭐' },
    { title: 'glowing star', character: '🌟' },
    { title: 'sparkles', character: '✨' },
    { title: 'collision', character: '💥' },
    { title: 'party popper', character: '🎉' },
    { title: 'confetti ball', character: '🎊' },
    { title: 'balloon', character: '🎈' },
    { title: 'trophy', character: '🏆' },
    { title: 'medal', character: '🏅' },
    { title: 'check mark', character: '✅' },
    { title: 'check mark button', character: '✔️' },
    { title: 'cross mark', character: '❌' },
    { title: 'warning', character: '⚠️' },
    { title: 'prohibited', character: '🚫' },
    { title: 'hundred points', character: '💯' },
    { title: 'light bulb', character: '💡' },
    { title: 'rocket', character: '🚀' },
    { title: 'hourglass done', character: '⌛' },
    { title: 'alarm clock', character: '⏰' },
    { title: 'stopwatch', character: '⏱️' },
    { title: 'timer clock', character: '⏲️' },
  ]);

  // Food & Drink
  specialCharacters.addItems('Emoji: Food', [
    { title: 'pizza', character: '🍕' },
    { title: 'hamburger', character: '🍔' },
    { title: 'hot dog', character: '🌭' },
    { title: 'taco', character: '🌮' },
    { title: 'burrito', character: '🌯' },
    { title: 'bread', character: '🍞' },
    { title: 'french fries', character: '🍟' },
    { title: 'popcorn', character: '🍿' },
    { title: 'coffee', character: '☕' },
    { title: 'teacup without handle', character: '🍵' },
    { title: 'beer mug', character: '🍺' },
    { title: 'clinking beer mugs', character: '🍻' },
    { title: 'wine glass', character: '🍷' },
    { title: 'cocktail glass', character: '🍸' },
    { title: 'birthday cake', character: '🎂' },
    { title: 'shortcake', character: '🍰' },
    { title: 'cookie', character: '🍪' },
    { title: 'chocolate bar', character: '🍫' },
    { title: 'candy', character: '🍬' },
    { title: 'lollipop', character: '🍭' },
    { title: 'doughnut', character: '🍩' },
    { title: 'ice cream', character: '🍨' },
  ]);

  // Animals & Nature
  specialCharacters.addItems('Emoji: Animals', [
    { title: 'dog face', character: '🐶' },
    { title: 'cat face', character: '🐱' },
    { title: 'mouse face', character: '🐭' },
    { title: 'rabbit face', character: '🐰' },
    { title: 'fox', character: '🦊' },
    { title: 'bear', character: '🐻' },
    { title: 'panda', character: '🐼' },
    { title: 'koala', character: '🐨' },
    { title: 'tiger face', character: '🐯' },
    { title: 'lion', character: '🦁' },
    { title: 'cow face', character: '🐮' },
    { title: 'pig face', character: '🐷' },
    { title: 'monkey face', character: '🐵' },
    { title: 'see-no-evil monkey', character: '🙈' },
    { title: 'hear-no-evil monkey', character: '🙉' },
    { title: 'speak-no-evil monkey', character: '🙊' },
    { title: 'unicorn', character: '🦄' },
    { title: 'bird', character: '🐦' },
    { title: 'penguin', character: '🐧' },
    { title: 'chicken', character: '🐔' },
    { title: 'hatching chick', character: '🐣' },
    { title: 'baby chick', character: '🐤' },
    { title: 'turtle', character: '🐢' },
    { title: 'bug', character: '🐛' },
    { title: 'butterfly', character: '🦋' },
    { title: 'bee', character: '🐝' },
    { title: 'lady beetle', character: '🐞' },
  ]);

  // Nature
  specialCharacters.addItems('Emoji: Nature', [
    { title: 'sunflower', character: '🌻' },
    { title: 'cherry blossom', character: '🌸' },
    { title: 'rose', character: '🌹' },
    { title: 'hibiscus', character: '🌺' },
    { title: 'tulip', character: '🌷' },
    { title: 'bouquet', character: '💐' },
    { title: 'four leaf clover', character: '🍀' },
    { title: 'seedling', character: '🌱' },
    { title: 'evergreen tree', character: '🌲' },
    { title: 'deciduous tree', character: '🌳' },
    { title: 'palm tree', character: '🌴' },
    { title: 'cactus', character: '🌵' },
    { title: 'mushroom', character: '🍄' },
    { title: 'sun', character: '☀️' },
    { title: 'crescent moon', character: '🌙' },
    { title: 'star', character: '⭐' },
    { title: 'rainbow', character: '🌈' },
    { title: 'cloud', character: '☁️' },
    { title: 'snowflake', character: '❄️' },
    { title: 'umbrella with rain drops', character: '☔' },
    { title: 'droplet', character: '💧' },
    { title: 'ocean wave', character: '🌊' },
  ]);

  // Travel & Places
  specialCharacters.addItems('Emoji: Travel', [
    { title: 'airplane', character: '✈️' },
    { title: 'automobile', character: '🚗' },
    { title: 'taxi', character: '🚕' },
    { title: 'bus', character: '🚌' },
    { title: 'train', character: '🚆' },
    { title: 'bicycle', character: '🚲' },
    { title: 'ship', character: '🚢' },
    { title: 'anchor', character: '⚓' },
    { title: 'camping', character: '🏕️' },
    { title: 'beach with umbrella', character: '🏖️' },
    { title: 'desert island', character: '🏝️' },
    { title: 'mountain', character: '⛰️' },
    { title: 'house', character: '🏠' },
    { title: 'office building', character: '🏢' },
    { title: 'castle', character: '🏰' },
    { title: 'wedding', character: '💒' },
    { title: 'Statue of Liberty', character: '🗽' },
    { title: 'globe showing Europe-Africa', character: '🌍' },
    { title: 'globe showing Americas', character: '🌎' },
    { title: 'globe showing Asia-Australia', character: '🌏' },
  ]);

  // Activities & Sports
  specialCharacters.addItems('Emoji: Sports', [
    { title: 'soccer ball', character: '⚽' },
    { title: 'basketball', character: '🏀' },
    { title: 'american football', character: '🏈' },
    { title: 'baseball', character: '⚾' },
    { title: 'tennis', character: '🎾' },
    { title: 'volleyball', character: '🏐' },
    { title: 'rugby football', character: '🏉' },
    { title: '8 ball', character: '🎱' },
    { title: 'trophy', character: '🏆' },
    { title: 'medal', character: '🏅' },
    { title: '1st place medal', character: '🥇' },
    { title: '2nd place medal', character: '🥈' },
    { title: '3rd place medal', character: '🥉' },
    { title: 'musical note', character: '🎵' },
    { title: 'musical notes', character: '🎶' },
    { title: 'microphone', character: '🎤' },
    { title: 'headphone', character: '🎧' },
    { title: 'guitar', character: '🎸' },
    { title: 'video game', character: '🎮' },
    { title: 'joystick', character: '🕹️' },
    { title: 'game die', character: '🎲' },
    { title: 'artist palette', character: '🎨' },
  ]);

  // Objects
  specialCharacters.addItems('Emoji: Objects', [
    { title: 'mobile phone', character: '📱' },
    { title: 'laptop', character: '💻' },
    { title: 'computer mouse', character: '🖱️' },
    { title: 'keyboard', character: '⌨️' },
    { title: 'printer', character: '🖨️' },
    { title: 'camera', character: '📷' },
    { title: 'video camera', character: '📹' },
    { title: 'television', character: '📺' },
    { title: 'electric plug', character: '🔌' },
    { title: 'battery', character: '🔋' },
    { title: 'magnifying glass', character: '🔍' },
    { title: 'locked', character: '🔒' },
    { title: 'unlocked', character: '🔓' },
    { title: 'key', character: '🔑' },
    { title: 'wrench', character: '🔧' },
    { title: 'hammer', character: '🔨' },
    { title: 'envelope', character: '✉️' },
    { title: 'incoming envelope', character: '📨' },
    { title: 'e-mail', character: '📧' },
    { title: 'memo', character: '📝' },
    { title: 'briefcase', character: '💼' },
    { title: 'file folder', character: '📁' },
    { title: 'calendar', character: '📅' },
    { title: 'pushpin', character: '📌' },
    { title: 'paperclip', character: '📎' },
    { title: 'scissors', character: '✂️' },
    { title: 'book', character: '📖' },
    { title: 'newspaper', character: '📰' },
    { title: 'money bag', character: '💰' },
    { title: 'dollar banknote', character: '💵' },
    { title: 'euro banknote', character: '💶' },
    { title: 'credit card', character: '💳' },
    { title: 'shopping cart', character: '🛒' },
    { title: 'gift', character: '🎁' },
  ]);

  // Flags (most common)
  specialCharacters.addItems('Emoji: Flags', [
    { title: 'Italy flag', character: '🇮🇹' },
    { title: 'United States flag', character: '🇺🇸' },
    { title: 'United Kingdom flag', character: '🇬🇧' },
    { title: 'France flag', character: '🇫🇷' },
    { title: 'Germany flag', character: '🇩🇪' },
    { title: 'Spain flag', character: '🇪🇸' },
    { title: 'Japan flag', character: '🇯🇵' },
    { title: 'China flag', character: '🇨🇳' },
    { title: 'Brazil flag', character: '🇧🇷' },
    { title: 'Canada flag', character: '🇨🇦' },
    { title: 'Australia flag', character: '🇦🇺' },
    { title: 'India flag', character: '🇮🇳' },
    { title: 'Russia flag', character: '🇷🇺' },
    { title: 'European Union flag', character: '🇪🇺' },
    { title: 'white flag', character: '🏳️' },
    { title: 'rainbow flag', character: '🏳️‍🌈' },
    { title: 'checkered flag', character: '🏁' },
  ]);
}
